### ISSUE TITLE
Review on 8/7's draft

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/draft-guide-jpa-intro#16]
- [x] The application that you will be working with is the Event Manager, which provides services for creating, retrieving, updating and deleting Event objects. => it feels that the "Event Manager" doesn't need to be backticked and cap'ed, simply leave it as "a event manager". Similarly for the "Event objects", it can be "events" or "event objects". Kind of prefer the first. 

- [x] The application uses an Embedded Derby database as a datastore for all the Event objects. => same here for "Event objects". 

- [x] If you want to learn more about Embedded Derby, see the official website. => official website should be change to the title for the website, ie, Derby Tutorial website. Or simply don't need the word "website". 

- [x] You will use JPA annotations to define an entity class whose fields are persisted to the database. Every entity object is managed by an EntityManager that will be injected into our Enterprise Java Bean (EJB). In this guide, you will learn how to use a container-managed EntityManager so you will not need to explicity begin, commit or rollback database transactions, the EJB container will manage the transaction boundaries for you. => Notice in this paragraph you talked about entity. If you had introduced the event object as event entity in the previous paragraph, that'll make this paragraph easier to follow. You did seem to use event entity later in the guide too. 

- [x] Avoid using the directional word, ie, "Add the following JPA annotations to the Event class in the src/main/java/io/openliberty/guides/jpaguide/models/Event.java file:". => also, specify the annotations to be added. Looks like there're quite some annotations, perhaps you provide the event class, then refer and talk about each annotation. What you have currently is not very clear.

- [x] Remove the "related guide" tag if there's no related guide.

**Comment by evelinec** [comment]
Sorry I didn't finish reviewing the whole guide, here're more items:

- [ ] The persistence unit is defined by the <persistence-unit name="jpa-unit" transaction-type="JTA"></persistence-unit> XML element. The name attribute is required and is used to identify the persistent unit. The transaction-type=”JTA” element specifies to use Java Transaction API (JTA) transactions. In a Java EE environment, the default is JTA if this element is not specified.

The following properties are used for creating the database tables.

<property name="eclipselink.ddl-generation" value="create-tables"/>
<property name="eclipselink.ddl-generation.output-mode" value="both" />

=> I wonder if it's clear enough to call out these xml elements by their names in this section. Having to list out their config block just to refer to them seem overwhelming. 

- [ ] To learn more about the ddl-generation properties, see the Java Persistence API (JPA) Extensions Reference for EclipseLink. => there's a version number to this link, wonder it may be a problem for the future? And the linked words seem too long, maybe just "JPA Extensions Reference for EclipseLink"? Not sure "for EclipseLink" is needed. 

- [ ] Similar situation as above for the "eclipselink.logging.level" properties. I think you don't need to list the "eclipselink.logging.level" properties block. Same with this link, "Java Persistence API (JPA) Extensions Reference for EclipseLink." being long. 

- [ ] If using the name or id of the xml element is okay, pls revisit for all of the places where xml elements are being described in the guide. ie, derbyJDBCLib, samplejpadatasource, etc

- [ ] The "samplejpadatasource" and "JPAGuide" names need to be renamed. Use something more meaning to the app, ie, eventjpadatasource, and EventDB? 

- [ ] CRUD is an abbreviation that defines the four basic functionalities that can be performed on a database: create, read, update and delete.

Create the src/main/java/io/openliberty/guides/jpaguide/dao/EventDao.java file:
=> there's no connection here as of why to create the EventDao.java class relates to the CRUD

- [ ] EventAppTest => renamed to EventEntityTest? 

- [ ] testCreatingDeletingNewEvent => includes retrieving/reading event too? It seem this function is missing in the test, if it's not mentioned in the test case name. 

- [ ] In the test class, where make sense, move the private methods in to an util or something? To make the test class cleaner and shorter.

**Comment by evelinec** [comment]
The points addressed are either good or obsolete due to the recent changes of this guide. 

@andrewdes did you consider the last point above?

**Comment by andrewdes** [comment]
@evelinec the test code was cleaned up and merged here: https://github.com/OpenLiberty/draft-guide-jpa-intro/commit/aa9a6967191074f2c29dfc8bff5cff5c87adc770
