### ISSUE TITLE
Review comments

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/draft-guide-jpa-intro#24]
Development question before the rest of my comments (as the answer might nullify some of my comments below). Is there a reason why the app uses an EJB container instead of JPA in CDI? I don't know how well these two examples map to the app in this guide but they seem similar (at a very quick glance): http://www.mastertheboss.com/jboss-frameworks/cdi/cdi-and-jpa-tutorial and https://www.sitepoint.com/cdi-weld-inject-jpa-hibernate-entity-managers/

The rest of my comments (which I'd already written):

What you'll learn
- [x] "container-managed" - I think the context here needs to be clearer. My first thought was Docker containers but it's actually talking about EJB containers. I think using the term "EJB container" first would make the context clearer.

- [x] It's not clear (from the introduction) what the EJB here is for and why EJB is being used in this app. Can this be made clearer?

Defining a JPA entity class
- [x] "Add JPA annotations to the Event class and all of its fields in the src/main/java/io/openliberty/guides/jpaguide/models/Event.java file:" should be "Create file xxxx" (using the standard wording we use in other guides. Then the user copies the entire class and creates the class (however we do it as standard for the guides) in the location in the `start` folder. There's no reason to provide the old version because the text below the snippet explains what's been added to make it a JPA entity class and why. I like the rest of the intro before that sentence - nice and clear.

  For most guides, the purpose of the guide app isn't for the reader to adapt an existing app. The aim is that they will build the app. But, in most guide apps, there are parts that are not relevant to learning about the key concepts addressed in the guide. That's why we have the `start` directory - it contains files that don't contribute to the learning. In this case, there's no reason for the `Event.java` file to be part of the `start` directory because the reader creates the file as part of learning about what it does.

- [x] "Lets break down the new annotations:" -> "Let's break down the annotations that are used in this JPA entity class:" (or similar). Note, also, the apostrophe. I like the table.

Configuring the `EntityManager`
- [x] I'm not sure I follow what an "`EntityManager` instance" is. Instance of what? And why does it need to be configured? I think this introductory paragraph (before creating the persistence.xml file) needs to be clearer. Okay, so I just noticed it's introduced a little more in the "What you'll learn" section but I'm still not clear why the word is highlighted (as opposed to just "entity manager" because I don't see the term used in any of the code. According to the Oracle docs it's an interface.

- [x] "Configuring the `EntityManager`" heading. It looks weird having highlighting in a heading. I'd suggest without the highlighting but I think the title needs to be clearer what the section is about.

- [x] "displayed in the WAS server log" - I don't think it should refer to the WAS server log? That's not it's name and we shouldn't be referring to WAS/WebSphere unless that's the exact name of the file. I think it'd be worth giving the name of the log file in the `target/..../servers...` directory structure (assuming that's what's being referred to) so that they can take a look at it.

- [ ] "A JTA transaction type requires a data source" - is this still part of configuring the EntityManager? Or should it be a separate "Configuring the data source" section? (I don't know - it just is a bit unclear that this is the start of a next bit - not critical though).

- [x] "This means that a Java Database Connectivity (JDBC) connection does not have to be specified in the persistence.xml file and instead the data source can be preconfigured in the server.xml." - It needs to be clearer why this is a good thing (I assume it is?). Also "preconfigured" should be "configured". 

- [x] "Configure the data source in the src/main/liberty/config/server.xml file:" - this should be 'Create the xxx/server.xml file:" etc. The previous paragraph explains that the data source is configured in there and the paragraphs after the snippet explain the relevant bits.

- [ ] Would it make sense to introduce the entity manager and CRUD etc before doing the entity manager configuration? ie swap the order of the Configuring the `EntityManager` and Performing CRUD operations using JPA sections. Does that cause problems or make no sense to a developer? I'm just thinking it might make it easier to see why you need to configure it if you've already used it in the app.

Style comments:

- [x] Think "Java Objects" should be "Java objects". "Object Relational Mapping" -> "object relational mapping (ORM)". There's no need to capitalise programming concepts.

- [x] "injected into our Enterprise Java Bean (EJB)." - make "our" into "the" - it reads oddly as it is ("our" is not used anywhere else - and is annoying if used everywhere - so just stick with "the").

- [x] "Every entity object is managed by an `EntityManager`" - It doesn't make sense to run the highlighted interface name into a sentence like this. Re-word eg "Every entity object is managed by an entity manager".

- [x] Use the Oxford comma in lists. So put a comma in "creating, retrieving, updating, and deleting event entities" (commas before 'and' and 'or' in lists of more than two items). See also the next example...

- [x] "In this guide, you will learn how to use a container-managed EntityManager so you will not need to explicity begin, commit or rollback database transactions, the EJB container will manage the transaction boundaries for you." -> "In this guide, you will learn how to use a container-managed EntityManager which means you do not need to explicitly begin, commit, or rollback database transactions because the EJB container manages the transaction boundaries for you." Don't talk about how the technology works in the future tense - it's not going to happen in the future - that's just how it works. Also, "roll back" as two words when used as a verb.

- [x] In the annotations table, "Specifies the generation strategy for the value of the primary key, strategy = GenerationType.AUTO indicates that the persistence provider will pick a strategy depending on the database used" doesn't make sense. Either the comma should be a full-stop/period, or there should say "which indicates" (depending on the meaning intended).

- [x] "oeration" - typo

**Comment by yeekangc** [comment]
I echo @lauracowen's comment or question around EJB.

We should position this guide as accessing and persisting data for microservices.  I am of the opinion that we should not place a dependency on EJB since JPA can be used on its own and in a microservices architecture, that should be the case.

We should refactor and decouple the use of the EJB feature IMO.

@gkwan-ibm @evelinec

**Comment by yeekangc** [comment]
Looks like #34 has been filed for my comments above re EJB.  Thank you.

**Comment by evelinec** [comment]
Remaining issues on this feedback:

- [ ] The "container-managed" still isn't very clear in the "what you'll learn" section. This sentence, "In this guide you will learn how to use a transaction-scoped container-managed persistence context EntityManager." has too many terms that aren't explained, "transactional-scoped", "container-managed".

- [ ] Still don't see the answer to the question, "why does it need to be configured?" in the "Configuring the EntityManager" section. Perhaps this sentence is to be reworded a bit, "The configuration of the EntityManager is defined by a persistence unit specified in the persistence.xml file." => "The EntityManager needs to be configured by a persistence unit specified in the persistence.xml file."?

**Comment by yeekangc** [comment]
+1 that "transaction-scoped container-managed persistence context EntityManager" is too terse and should be reworded.  I don't think we should explain all the terms in this section either.  Should focus on what would make sense to users as an Intro guide.

**Comment by evelinec** [comment]
The rest of the fixes are good.
