### ISSUE TITLE
Review on 9/7's draft

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/draft-guide-jpa-intro#29]
Title and Intro: 
- the title doesn’t seem broad enough to cover what’s in the abstract, ie, mapping java objects to the db and CRUD. 
- it feels that the intro is not enough. ie, can explain ORM more? 
- state the benefit of using JPA separately to increase its value? ie, eliminates the burden of having to write SQL code when performing database operations. 
- also are there more benefits of using JPA? perhaps answer the question of how data processing work without using JPA and then why JPA makes things easier/better? 
- not sure what “container-managed entity manager” means on its own. perhaps there are different type of entity managers, and this is one of them? Then I’d say should briefly mention the different types, then say this guide will use the container-manage type.
- “The application that you will be working with is the event manager, which provides services for creating, retrieving, updating, and deleting event entities.” I think this sentence can be broken down into two. ie, “The application that you will be working with is an event manager.” Then I think user will be instructed to build the CRUD operations with the database. So perhaps, describe how JPA work and then mention the CRUD services that user will be building. 

Defining a JPA entity class
- the @NamedQuery annotation probably needs a more explanation, why is it used here?
- the @Id annotation description doesn’t start with a verb

**Comment by andrewdes** [comment]
@evelinec yes, it has been addressed.

**Comment by evelinec** [comment]
Ok. The others look good. Just this one didn't have any change: 

- the @id annotation description doesn’t start with a verb

**Comment by andrewdes** [comment]
Changed in https://github.com/OpenLiberty/draft-guide-jpa-intro/commit/45525fef583a4a78dd902896506b3a01acd69ae6
