### ISSUE TITLE
Need to fix the abstracts and intro sentence

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/draft-guide-jpa-intro#46]
These should better reflect what the guide covers:

_:page-description: Learn how to perform CRUD operations using JPA
Learn how to map Java objects to database tables and perform CRUD operations using JPA._

The first one is the abstract that shows in the card for the guide under all guides page and the second one is the abstract under the title.

Consider something along the line of "Learn how to use Java Persistence API to access and persist data to a database for your microservices".

---

For the below:

_You will learn how to use the Java Persistence API (JPA) to map Java objects to database tables and
perform create, read, update and delete (CRUD) operations in your microservices._

We should call out the target too i.e. it is against a (relational) database.

**Comment by yeekangc** [comment]
@gkwan-ibm @evelinec

**Comment by andrewdes** [comment]
Abstract and opening sentence were updated here: https://github.com/OpenLiberty/draft-guide-jpa-intro/commit/ec88e4f8558e9481284e7c4c8c4a1dfa08417bab. Opening sentence was further improved to ensure it was evident that you are working with data in database (https://github.com/OpenLiberty/draft-guide-jpa-intro/commit/45525fef583a4a78dd902896506b3a01acd69ae6)
