### ISSUE TITLE
Fix the java code

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/draft-guide-jpa-intro#51]
Format all java code formatted properly
e.g. 
- in Event.equals() method missing space
```
        if(name == null) {
            if(other.name != null)
                return false;
        }else if(!name.equals(other.name))
            return false;
``` 
- EventEntityTest
  - better have a new empty line in between
```
import io.openliberty.guides.models.Event;
public class EventEntityTest {
```
  - missing space
```
    private JsonObject findTestEvent(JsonArray events){
        for(int i = 0; i < events.size(); i++){
```

**Comment by yuval105** [comment]
Can I go for it? This is my first time contributing.

**Comment by gkwan-ibm** [comment]
@yuval105 I merged your contribution. thanks

**Comment by gkwan-ibm** [comment]
@andrewdes  Something still need to be fixed:
- no line should longer than 88 characters
- even one line
```
    else 
       return;
```
block as
```
    else {
        return;
    }
```

**Comment by andrewdes** [comment]
Wrapped lines at 88 chars, added brackets to one line statements (if & or) and removed unnecessary spaces. Merged here: https://github.com/OpenLiberty/draft-guide-jpa-intro/commit/454cc01fd6f3486e7b0f214c137782220bb47de6
