### ISSUE TITLE
Feedback for "Performing CRUD operations using JPA"

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/draft-guide-jpa-intro#55]
The paragraph below under this section is difficult to understand:

_Every entity object has a lifecycle that consists of four states: new, managed, detached and removed. Whenever a new Event object is created its state will be new, meaning that it is not mapped to a row in the database table and is not associated with an EntityManger. Managed entities are entities that have been persisted, or fetched by find() or a query, and are managed by the EntityManager. This means that they are actively tracked by the persistence context. Detached entities are no longer managed by a persistence context. When using a container-managed EntityManager, entities automatically become detached at the end of transaction boundaries. Lastly, removed entities will be marked for removal and will be deleted from the database upon transaction commit._

Its relationship to the rest of the section is difficult to work out too.

Should consider revision to make it easier to understand and make clear its relationship to doing CRUD operations.

**Comment by andrewdes** [comment]
After reworking the guide, the paragraph in question is no longer in the guide.
