### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by proubatsis** [OpenLiberty/draft-guide-jpa-intro#63]
# Peer Review

- [x]  Working instruction and sample code
- [x]  Quality of code (best coding practices)
- [x]  Quality and presentation of guide according to Structure and Style Guideline
- [x]  Consistency of guide with template and other guides
- [x]  Examples with the right outcomes are provided
- [x]  Example with the wrong outcomes, if any, are provided
- [ ]  Check that all licensing statements are properly stated in all files
- [x]  Check that the pom.xml, server.xml, etc files are clean up
- [x]  Check that the directories are properly structured

**Comment by proubatsis** [comment]
# Notes

* No error message when the input date is before the current date, the form just does nothing. This is confusing at first glance.
* Fix the paragraph inside of the codeblock (you already noticed this yourself, just adding it in the issue for completeness)
* `server.xml` missing under `start/` causing `mvn install` to fail at `Building and running the application`
* In `Running the tests` why do you say to stop the server **again**?
* Tests failed for me
```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running it.io.openliberty.guides.event.EventEntityTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 3.473 sec <<< FAILURE! - in it.io.openliberty.guides.event.EventEntityTest
testCRUD(it.io.openliberty.guides.event.EventEntityTest)  Time elapsed: 3.468 sec  <<< ERROR!
java.lang.NullPointerException: null
	at it.io.openliberty.guides.event.EventEntityTest.testCRUD(EventEntityTest.java:56)


Results :

Tests in error: 
  EventEntityTest.testCRUD:56 NullPointer

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0
```

* License statements missing from:
  * server.xml
  * persistence.xml

* Line 119 in `EventService.java` is too long

* Based on conventions followed in other guides `EventService.java` should be named `EventResource.java`

**Comment by andrewdes** [comment]
@proubatsis Feedback was addressed and fixed here: https://github.com/OpenLiberty/draft-guide-jpa-intro/pull/65

License statements were not added to `server.xml` or `persistence.xml` since deemed unnecessary, `Running the tests` was not changed since it currently follows the guides template. The rest of the feedback was addressed.
