### ISSUE TITLE
Review feedback

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/draft-guide-jpa-intro#64]
- [x] The objective of this guide should show to the readers what files are they need to create (or concern), so that they can create a JPA microservice without GUI.  The content (Readme) should mention and explain all those files. I guess they should be
    - Event 
    - EventDao 
    - EventService (the rest service, right?)
    - EventApplication ???
    - persistence.xml
    - server.xml (JDBC and DataSources) ???
- [x] Following paragraph should be under the source first in the section
    - The EventDao.java class has a method for each CRUD operation, so let’s break them down:
- [x] Because the application in this guide contain UI and JPA microservice, the source should  be organized  clearly
    - Page* classes should be under ui package
        - e.g. io.openliberty.guides.ui.facelets
    - URLMapper? UI or JPA microservice code?
- [ ] Add comment to each class to explain its purpose (especially the UI classes because they are not described in Readme)
- [x] Is it important to explain EntityManager in EventDao? It is mentioned in Readme several places but it only appears in  EventDao as an private variable.

**Comment by gkwan-ibm** [comment]
@yeekangc @evelinec

**Comment by yeekangc** [comment]
We should not and do not need to list all files that will be created.  But, we should clearly explain and call out what the user will do.  Yes, the focus is on a service that uses JPA to access backend data -- this should be clear from the get go and the whole guide should be organized around it.

**Comment by yeekangc** [comment]
Additional comments ...

_Content_
The basic flow is this: You start with a object model of your data and then, you annotate it to map it to what you have in the database; Use the entity manager to write the operations that you need to perform; Setup your JPA configuration, which is basically your persistence.xml that defines the backend you (the entity manager) will be working with.

_Code_
- Consider naming the persistence unit with a more specific name like EventApp, which should help in mapping it to what it is being used for.

- The test code can be refactored to make the code cleaner.

**Comment by andrewdes** [comment]
@yeekangc the paragraph being displayed in a copy block has already been fixed and merged. 

I will take the other feedback into account and re-adjust the flow/content of the guide.

**Comment by gkwan-ibm** [comment]
@andrewdes would you follow up the following?
- [ ] refactor the packages as
  - io.openliberty.guides.event.dao
  - io.openliberty.guides.event.models
  - io.openliberty.guides.event.resources
  - io.openliberty.guides.event.client
  - io.openliberty.guides.event.ui.*
- [ ] define EventTest as an abstract class
- [ ] add message to all the assert statement
  - e.g. assertEquals("Get event with an invalid id should return empty list but wasn't.", getIndividualEvent(-1).isEmpty(), true);

**Comment by yeekangc** [comment]
@andrewdes, the Test methods can be further refactored too IMO.  I see common code that is duplicated in multiple spots.

**Comment by andrewdes** [comment]
Changes were merged here: https://github.com/OpenLiberty/draft-guide-jpa-intro/commit/32874e55619a11115f320b6cc39502a638ce9c4e. This includes the refactoring of the package, defining the EventTest abstract class, adding messages to assertion statements, and further test refactor. 

Still left to do: Add comments to UI classes 

The rest of feedback in this issue has been addressed elsewhere or is no longer relevant due to the guide refactor.
