### ISSUE TITLE
Peer Review - 11/14/2018

### ISSUE THREAD

**Issue by andrewdes** [OpenLiberty/draft-guide-jpa-intro#77]
- [x] Working instruction and sample code
- [x] Quality of code (best coding practices)
- [x] Quality and presentation of guide according to Structure and Style Guideline
- [x] Consistency of guide with template and other guides
- [x] Examples with the right outcomes are provided
- [x] Example with the wrong outcomes, if any, are provided
- [x] Check that all licensing statements are properly stated in all files
- [x] Check that the pom.xml, server.xml, etc files are clean up
- [x] Check that the directories are properly structured
- [x] Test the guide on 3 platforms: Mac, Win, Liniux
- [x] If any URL visits, try them on different browsers: Firefox, Chrome, Safari
- [x] If any URL visits, try curl command where applicable

**Comment by proubatsis** [comment]
# Mac
- [ ] Working instructions and sample code
- [ ] Examples with the right outcomes are provided
- [ ] Examples with wrong right outcomes are provided, if any are provided
- [ ] Visit URL
  - [ ] Chrome
  - [ ] Firefox
  - [ ] Safari

# Windows
- [ ] Working instructions and sample code
- [ ] Examples with the right outcomes are provided
- [ ] Examples with wrong right outcomes are provided, if any are provided
- [ ] Visit URL
  - [ ] Chrome
  - [ ] Firefox
  - [ ] Microsoft Edge
  
# Ubuntu
- [ ] Working instructions and sample code
- [ ] Examples with the right outcomes are provided
- [ ] Examples with wrong right outcomes are provided, if any are provided
- [ ] Visit URL
  - [ ] Chrome
  - [ ] Firefox

**Comment by proubatsis** [comment]
![image](https://user-images.githubusercontent.com/8409464/48513140-12b5af00-e829-11e8-88a0-d0fc7ffc412e.png)
 The dashes do not look consistent with the other browser on Microsoft Edge.

**Comment by proubatsis** [comment]
Doesn't work on Linux, this fixes it: https://github.com/OpenLiberty/guide-getting-started/pull/35/files

**Comment by gkwan-ibm** [comment]
@andrewdes Would you change the following plugins version to 3.0.0-M1 in the pom.xml and run ```mvn install``` for all 3 platforms? 
```
        <version.maven-surefire-plugin>3.0.0-M1</version.maven-surefire-plugin>
        <version.maven-failsafe-plugin>3.0.0-M1</version.maven-failsafe-plugin>
```

**Comment by gkwan-ibm** [comment]
@andrewdes Would you update the maven-surefire-plugin and maven-failsafe-plugin version to 3.0.0-M1 in pom.xml and try all 3 platforms ```mvn install```?

**Comment by gkwan-ibm** [comment]
- Need to address the ubuntu issue 
- will ask SME to take a quick review

**Comment by andrewdes** [comment]
Updated the maven-surefire-plugin and maven-failsafe-plugin to 3.0.0-M1 (as seen here: https://github.com/OpenLiberty/draft-guide-jpa-intro/pull/78) and `mvn install` worked on Windows, Mac and Linux.

**Comment by andrewdes** [comment]
@proubatsis The update was merged here: https://github.com/OpenLiberty/draft-guide-jpa-intro/commit/a924be6c43749c1301dd8931836caeb27534b511
