### ISSUE TITLE
Tommy's Feedback

### ISSUE THREAD

**Issue by wojtczat** [OpenLiberty/draft-guide-jpa-intro#83]
I don't have many complaints for this guide. I loved how descriptive it was compared to the other guides. This made it very easy to understand and work through quickly. The 20 minute estimated completion time was also accurate. One fault with the guide is perhaps the tests. When I create an event and do not delete it a test will fail. I figured this may not be intended as many users may not delete all of the events they have created before running `mvn verify`

**Comment by andrewdes** [comment]
The issue with the test was fixed and merged here: https://github.com/OpenLiberty/draft-guide-jpa-intro/commit/32874e55619a11115f320b6cc39502a638ce9c4e

**Comment by wojtczat** [comment]
Looks good
