### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by justineechen** [OpenLiberty/draft-guide-jpa-intro#9]
**Overall**

**What you'll learn**

- [x] These two sentences about what the guide will teach aren't really consistent, maybe you can find a way to tie the two together.

> "You will learn how to use the Java Persistence API to map Java objects to database tables." 
> "Learn how to perform CRUD operations using JPA"

-  Many acronyms are introduced here (JPA, ORM, POJO, JTA) and mentioned throughout the guide, I felt that I had to go back a lot to remember them and it was difficult to follow along when I didn't understand the acronym. 
- [x] I think ORM can be removed since it is only mentioned one time, or you can remove the acronym since we never use the term again.
ex. 
> "JPA eliminates the burden of writing SQL code when performing database operations."

- [x] I'm not sure if it's necessary to include the Embedded Derby link, I feel like it disturbs the flow of the paragraph.

- [x] The following sentence could be simplified

> You will use JPA annotations to define a Plain Old Java Object (POJO) class as an entity class whose persistent fields are persisted to the datastore.

> You will use JPA annotations to define an entity class whose fields are persisted to the data store.

- [x] What are transaction boundaries? Is the user supposed to know what this term means already?

- [x] The following sentence could be simplified.

>  A container-managed EntityManager requires the use of the Java Transaction API (JTA). By using JTA transactions, the Event Manager application does not have to pass references to EntityManager instances from one component to another.

**Getting Started**
- [x] This sentence may be more clear in the following way
> "Before being able to use JPA to store Java objects in a database, an entity class must be defined."
> "An entity class must be defined before you are able to use JPA to store Java objects in a database."

- [x] I think it would be useful to show the persistence of the events by telling the user that the events will still be there after the server is stopped and ran again.

**Accessing data using JPA**
- [x] I feel like the paragraphs explaining the persistence-unit and data source configuration is a little redundant because the names of the attributes are self-explanatory.

**Performing CRUD operatoins using JPA**
- [x] Typo "The persistence" context manages a set of..."
- [x] Are all of the methods that you are describing essential to what the user needs to learn for the guide? If not, maybe you should remove the descriptions because there is a lot of information in these couple of paragraphs.

**Comment by evelinec** [comment]
@justineechen can you verify if all of your feedback has been addressed?
